### ISSUE TITLE
slide elements counted as 2x item length

### ISSUE THREAD

**Issue by gabestev** [geex-arts/ngx-flickity#1]
I found conflict at flickity.directive.ts [Line 25](https://github.com/geex-arts/ngx-flickity/blob/dev/src/components/flickity/flickity.directive.ts#L25) and [Line 29](https://github.com/geex-arts/ngx-flickity/blob/dev/src/components/flickity/flickity.directive.ts#L29)

I'm newbie to NPM package, so i can't do PR to push my patch.

In the end, i copy your source into my Angular project.

Thanks!

**Comment by charlesharvey** [comment]
Thanks @f1nality for your hard work.
I have this same problem as @gabestev . Flickity thinks there are twice as many slides as there are.

**Comment by danielswiatek** [comment]
@gabestev can you tell me what do you do to fix?

**Comment by dottodot** [comment]
Just don't use the flickityChild directive as that is just duplicating slides.

**Comment by gabestev** [comment]
@danielswiatek i think its already been fixed. i can't find the line again.
perhaps this issue should be closed
